# Generated by Django 2.1.4 on 2018-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0008_auto_20181129_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_locs',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
