# Generated by Django 2.1.2 on 2018-12-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0009_item_item_locs'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='distance_to_origin',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
