# Generated by Django 2.1.2 on 2018-12-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0010_item_distance_to_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='distance_to_origin',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_locs',
        ),
    ]
