# Generated by Django 2.1.2 on 2018-12-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_app', '0011_auto_20181215_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemResultsRestView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locitem', to='shopper_app.Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemloc', to='shopper_app.GeoLoc')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemresultsrestview',
            unique_together={('location', 'item')},
        ),
    ]
